direct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('api/',include('direct.api.urls'))
]

kitapproje/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kullanici/',include('kullanici.urls')),
    path('direct/',include('direct.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

kullanici/api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.routers import DefaultRouter
from kullanici.api.views import UserViewSet,RegisterApiView,TestApiView,ProfileAPIView

router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user')

urlpatterns = [
    path('register',RegisterApiView.as_view(),name="aregister"),

    path('api-auth/',include('rest_framework.urls')),
    path('api/rest-auth/',include('rest_auth.urls')),
    path('test',TestApiView.as_view()),
    path('guncelle',ProfileAPIView.as_view(),name='profile-update')

]

kullanici/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import LoginView, KayitView,CreateChatView ,SingleTicketView, ActivateView, password_reset_request,LogoutView,ProfileView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register', KayitView, name='register'),
    path('login', LoginView, name='login'),
    path("logout",LogoutView,name="logout"),
    path('api/', include('kullanici.api.urls')),    
    path('activate/<uidb64>/<token>', ActivateView.as_view(), name='activate'), # üyelik aktifleştirme
    path("profile/",ProfileView,name="profile"),
    path("destek/",CreateChatView,name="destek"),
    path("destek/talep/<int:id>/",SingleTicketView,name="single-ticket"),
    ###################### ŞİFRE SIFIRLAMA ###########################
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", password_reset_request, name="password_reset")

]

kullanici/models.py
from django.db import models

from django import forms
# Create your models here.
#from .forms import ProfilUpdateForm
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from kitapproje.send_mail import mail_gonder
from django.templatetags.static import static
from django.contrib.auth.models import AbstractUser
from django.core.validators import validate_email
from django.db.models.signals import post_save,pre_save
from django.contrib.auth.password_validation import validate_password
from time import time
import random
from django.conf import settings
from django.dispatch import receiver
import re,os
def name_validator(value):
    if not value.isalpha():
        raise ValidationError("Bu Alan Sadece harflerden oluşmalıdır")
def pass_validator(value):
    #validate_password(value)
    if len(value) < 8 or len(value) > 100:
        raise ValidationError("Şifreniz 8 karakterden uzun 100 karakterden kısa olamaz")

    if re.search('[0-9]', value) is None:
        raise ValidationError("Şifrenizde En Az Bir Sayı Bulunmalıdır")

    if re.search('[A-Z]', value) is None:
        raise ValidationError("Şifrenizde En Az Bir Büyük Harf Bulunmalıdır")

    else:
        pass
def il_ilce_validator(value):
    p = static('js/kullanici/il-ilce.txt')
    if "i" in value:
        value = value.replace("i","İ")
    value = value.upper()
    #value = value.replace("I","İ")



    BASE_DIR = settings.BASE_DIR
    dirs = os.path.join(BASE_DIR,p[1:])
    print(dirs)
    with open(dirs,"r",encoding="utf-8") as f:
        data = f.read()

        if value in data:
            return value
        else:
            raise ValidationError("Lütfen Doğru Seçim Yapınız")
def phone_validator(value):
    if value is None or len(value.replace("-","")) != 10 or not value.replace("-","").isnumeric():
        #self.add_error("phone", "Numara Formatı Doğru Değil")
        raise ValidationError("Numara Formatı Doğru Değil")

        raise ValidationError("")
def email_validator(value):
    pass



class User(AbstractUser):
    first_name = models.CharField(_('first name'), max_length=150, blank=True,validators=[name_validator])
    last_name = models.CharField(_('last name'), max_length=150, blank=True,validators=[name_validator])
    email = models.EmailField(_('email address'), blank=True,validators=[email_validator],unique=True)
    password = models.CharField(_('password'), max_length=128,validators=[pass_validator])
    #password2 = models.CharField(_('password again'), max_length=128, validators=[pass_validator])
    adres = models.TextField(max_length=500, blank=False)
    il = models.CharField(max_length=40, blank=False,validators=[])
    ilce = models.CharField(max_length=40, blank=False,validators=[])
    phone = models.CharField( max_length=12,validators=[phone_validator],unique=True)
    def save(self, *args, **kwargs):

        super(User, self).save(*args,**kwargs)

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    image = models.ImageField(blank=True,null=True,upload_to="profile_photos/")
    #bg_color = models.CharField(max_length=50,blank=True,null=True)

def add_username(sender,instance,created,**kwargs):

    if created:
        user = User.objects.get(id=instance.id)
        if not user.is_superuser:
            user.username = user.first_name+user.last_name+str(int(time()))
            user.save()
            #image_colors = ["#33D4FF","#ff0000","#cc0066","#00b300","#ff9900","#0000e6"]
            #bg_color = random.choice(image_colors)
            Profile.objects.create(user=instance,image="book.jpg")
            mail_gonder(user, body="Üyelik onayınız için aşağıdaki linke tıklamanız gerekmektedir.")

def user_check_mail_exists(sender,instance,**kwargs):
    if instance.id is None:
        # yani user modeli daha oluşturulmadıysa
        value = instance.email
        email = value.lower()
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email Sistemde Kayıtlı.")


post_save.connect(add_username,sender=User)
#pre_save.connect(user_check_mail_exists,sender = User)

kullanici/forms.py
from django.db import models
from django import forms
from django.forms import ModelForm
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
import json
from django.core.validators import validate_email
from django.contrib.auth.password_validation import validate_password
from django.forms import ValidationError
from django.templatetags.static import static
import re,os
from .models import User
#from django.core.exceptions import ValidationError
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
#class LoginForm(forms.)
class IlIlceChoiceField(forms.ChoiceField):
    def validate(self, value):
        pass
    # def validate(self, value):
    #     p = static('js/kullanici/il-ilce.txt')
    #     #content = p.readlines()
    #     with open(p[1:],"r",encoding="utf-8") as f:
    #         data = f.read()
    #         if value in data:
    #             return value
    #         else:
    #             raise ValidationError("Lütfen Doğru Seçim Yapınız")
             
class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=20,label="İsim")
    last_name = forms.CharField(max_length=20,label="Soyisim")
    email = forms.EmailField(max_length=50,label="Email")
    il = IlIlceChoiceField(label="İl")
    ilce = IlIlceChoiceField(label="İlçe",widget=forms.Select())
    phone = forms.CharField( max_length=12,label="Telefon No")
    adres = forms.CharField(max_length=300,widget=forms.Textarea())
    password = forms.CharField(label="Parola", widget=forms.PasswordInput, help_text="Parolanızı girin")
    sifre2 = forms.CharField(label="Parola Tekrar",widget=forms.PasswordInput,help_text="Parolanızı tekrar girin")
    password2 = None
    
    class Meta:
        model = User
        fields = ('first_name','last_name','phone','email','il','ilce','password','sifre2','adres')
    
        # labels = {
        #     "first_name": "İsim",
        #     "last_name" : "Soyisim",
        #     "email": "E-mail",
        #     "phone": "Telefon",
        #
        #
        # }
    def __init__(self,*args,**kwargs):
        super(RegisterForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class':'form-control'}
            self.fields[field].required = True


        self.fields["email"].widget.attrs["placeholder"] = "test@deneme.com"
        self.fields["first_name"].widget.attrs["placeholder"] = "Adınız"
        self.fields["last_name"].widget.attrs["placeholder"] = "Soyadınız"
        self.fields["sifre2"].widget.attrs["placeholder"] = "Şifreniz Tekrar"
        self.fields["il"].widget.attrs["placeholder"] = "İl Seçiniz"
        #self.fields["il"].widget.attrs["id"] = "il_select"
        #self.fields["ilce"].widget.attrs["id"] = "ilce_select"
        self.fields["ilce"].widget.attrs["placeholder"] = "İlçe Seçiniz"
        self.fields["adres"].widget.attrs["placeholder"] = "Adres Giriniz"
        self.fields["phone"].widget.attrs["placeholder"] = "(5__)-___-____"
        self.fields["phone"].widget.attrs["class"] += " input-mask"
        self.fields['adres'].widget.attrs['rows'] = 7
        self.fields["password1"].required = False

      





    def clean(self):
 
       
        cleaned = self.cleaned_data
        print("Cleaned",self.cleaned_data)
        sifre = cleaned.get("password")
        tekrar_sifre = cleaned.get("sifre2")
        if sifre is None or tekrar_sifre is None:
            #self.add_error("password1","Şifre Alanı Boş Bırakılamaz")
            #self.add_error("sifre2", "Şifre Alanı Boş Bırakılamaz")
            raise ValidationError("")
        if sifre != tekrar_sifre:
            self.add_error("password","Şifreler Uyuşmuyor")
            self.add_error("sifre2", "Şifreler Uyuşmuyor")
            raise ValidationError("")

    def clean_phone(self):
        
        phone = self.cleaned_data["phone"]

        return phone.replace("-","")

    # def clean_email(self):
    #
    #     email = self.cleaned_data["email"]
    #     email = value.lower()
    #     if User.objects.filter(email=email).exists():
    #
    #         raise forms.ValidationError("Email Sistemde Kayıtlı.")
    #     return email


class LoginForm(forms.Form):
    email = forms.CharField(required=True,max_length=40,label="Email",
                            widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email Adresini Giriniz'}))
    password = forms.CharField(required=True,max_length=40,label="Password",
                            widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Şifrenizi Giriniz'}))

    # def clean(self):
    #     email = self.cleaned_data.get("email")
    #     password = self.cleaned_data.get("password")
    #     validate_email(email)
    def clean_email(self):
        email = self.cleaned_data.get("email").strip()
        validate_email(email)
        return email
    def clean_password(self):
        password = self.cleaned_data.get("password")
        validate_password(password)
        return password












class ProfilUpdateForm(forms.ModelForm):
    #password = forms.CharField(required=False,max_length=40,label="Yeni Şifre",
     #                       widget=forms.PasswordInput())
    #password_again = forms.CharField(required=False,max_length=40,label="Şifre Tekrar",
    #                        widget=forms.PasswordInput())
    il = IlIlceChoiceField(label="İl")
    ilce = IlIlceChoiceField(label="İlçe",widget=forms.Select())
    resim = forms.ImageField()
    class Meta:
        model = User
        fields = ['resim','first_name','last_name','email','phone','il','ilce','adres']



    def __init__(self,*args,**kwargs):
        super(ProfilUpdateForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class':'form-control'}
            #self.fields[field].required = False


        self.fields["resim"].required = False
        self.fields["first_name"].widget.attrs["placeholder"] = "Adınız"
        self.fields["last_name"].widget.attrs["placeholder"] = "Soyadınız"
        #self.fields["password"].widget.attrs["placeholder"] = "Yeni Şifre"
        #self.fields["password_again"].widget.attrs["placeholder"] = "Şifre Tekrar"
        self.fields["email"].widget.attrs["readonly"] = True
        self.fields["phone"].widget.attrs["placeholder"] = "(5__)-___-____"
        self.fields["phone"].widget.attrs["class"] += " input-mask"
        self.fields['adres'].widget.attrs['rows'] = 7

    # def clean(self):
    #
    #     cleaned = self.cleaned_data
    #     print("Cleaned", self.cleaned_data)
    #     sifre = cleaned.get("password")
    #     tekrar_sifre = cleaned.get("password_again")
    #     if sifre is None or tekrar_sifre is None:
    #         self.add_error("password","Şifre Alanı Boş Bırakılamaz")
    #         self.add_error("password_again", "Şifre Alanı Boş Bırakılamaz")
    #         raise ValidationError("")
    #     if sifre != tekrar_sifre:
    #         self.add_error("password", "Şifreler Uyuşmuyor")
    #         self.add_error("password_again", "Şifreler Uyuşmuyor")
    #         raise ValidationError("")

kullanici/api/views.py
from rest_framework.generics import ListAPIView,CreateAPIView,RetrieveAPIView,RetrieveUpdateAPIView,get_object_or_404
from .serializers import RegisterSerializer,UserSerializer

from kullanici.models import User
from .permissions import NotAuthenticated
from rest_framework.response import Response
from time import time
from rest_framework import viewsets,mixins
from rest_framework.permissions import IsAuthenticated

class RegisterApiView(CreateAPIView):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer
    permission_classes = [NotAuthenticated,]
    lookup_field = 'email'
    lookup_value_regex = '[\w@.]+'
    # def put(self,request,*args,**kwargs):
    #     return self.update(request,*args,**kwargs)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer
    lookup_field = 'email'
    lookup_value_regex = '[\w@.]+'
    permission_classes = [NotAuthenticated,]


class TestApiView(ListAPIView):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer
    permission_classes = [IsAuthenticated]

    # def put(self,request,*args,**kwargs):
    #     return self.update(request,*args,**kwargs)

class ProfileAPIView(RetrieveUpdateAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer
    queryset = User.objects.all()
    def get_object(self):
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset,id=self.request.user.id)
        return obj

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

templates/kullanici/profile/profile.html
{% extends 'kullanici/profile/profile_base.html' %}

{% load static %}

{% block profile_body %}
<form xmlns="http://www.w3.org/1999/html" method="POST" action="{% url 'profile' %}" enctype="multipart/form-data">
  {% csrf_token %}

    {% for field in form %}


   {% if field.name == 'resim' and request.user.profile.image != 'default.jpg' %}
   <div class="bg-secondary rounded-3 p-4 mb-4">
       <div class="d-flex align-items-center">
       <img src="{{ request.user.profile.image.url }}" class="rounded" width="70" alt="">


                <div class="ps-3">
                  <label class="btn btn-light btn-shadow btn-sm mb-2  btn-file">
                  <i class="ci-loading me-2"></i>Change avatar <input type="file" name="resim" id="id_resim" style="display: none;">
                </label>


                  <div class="p mb-0 fs-ms text-muted">Upload JPG, GIF or PNG image. 300 x 300 required.</div>
                </div>
              </div>
            </div>

  <div class="row gx-4 gy-3">
      {% elif field.name == 'resim' %}
        <div class="bg-secondary rounded-3 p-4 mb-4">
       <div class="d-flex align-items-center">
           <div class=" rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><span class="badge bg-warning position-absolute end-0 mt-n2" data-bs-toggle="tooltip" title="Reward points"></span>

            <p class="" id="profileImage" style="background-color:{{ request.user.profile.bg_clor }}" ><span class="text text-center">{{ request.user.first_name.0}}{{request.user.last_name.0}}</span></p></div>


                <div class="ps-md-3">
                  <label class="btn btn-light btn-shadow btn-sm mb-2  btn-file">
                  <i class="ci-loading me-2"></i>Change avatar <input type="file" id="id_image" style="display: none;">
                </label>


                  <div class="p mb-0 fs-ms text-muted">Upload JPG, GIF or PNG image. 300 x 300 required.</div>
                </div>
</div>          </div>




  <div class="row gx-4 gy-3">
      {% elif field.name == 'adres' %}
      <div class="col-md-12">
                <label class="form-label" for={{ field.id_for_label }}>{{ field.label }}</label>
                {{ field }}
                  {% include 'base/form_errors.html' %}
              </div>
{% else %}


              <div class="col-md-6">
                <label class="form-label" for={{ field.id_for_label }}>{{ field.label }}</label>
                {{ field }}
                  {% include 'base/form_errors.html' %}
              </div>


              {% endif %}

              {% endfor %}

   </div>
  <br>
              <div class="col-12">
                <hr class="mt-2 mb-3">
                <div class="d-flex flex-wrap justify-content-between align-items-center">
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="subscribe_me" checked>
                    <label class="form-check-label" for="subscribe_me">Subscribe me to Newsletter</label>
                  </div>
                  <input class="btn btn-primary mt-3 mt-sm-0" type="submit" value="Update profile">
                </div>
              </div>
            </div>

          </form>
        <div hidden id="il_div">{{form.il.value }}</div>
        <div hidden id="ilce_div">{{form.ilce.value }}</div>

{% endblock %}

 {% block javascript %}
<script src="{% static 'js/jquery.letterpic.min.js' %}"></script>
<script type="text/javascript">
$(".demo").letterpic({

  // an array of colors
  colors: ["#33D4FF","#ff0000","#cc0066","#00b300","#ff9900","#0000e6"],

  // an array of gradients


  // font family
  font: 'Arial',

  // 'color', 'images' or 'gradients'
  fill: 'color',

  // color of image overlay


  // font color
  fontColor: '#fff',

  // font size
  fontSize: .45

});

</script>

{% endblock %}

{% block vue %}
{% endblock %}

    {% block js %}
    <script>
    if ("{{form.il.value}}"!="None"){
        console.log("{{form.il.value}}");
        var il = "{{form.il.value}}";
        $('#il_select option[value=İSTANBUL]').attr('selected','selected');


    }
    //console.log("{{form.il.value}}"


     </script>


        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js" type="text/javascript"></script>



      <script src="{% static 'js/kullanici/profile.js' %}"></script>






    {% endblock %}

templates/kullanici/profile/profile_base.html
 {% extends 'base/base.html' %}
 {% load static %}
{% block css %}
 <link rel="stylesheet" media="screen" href="{% static 'css/kullanici/profile.css' %}">
 {% endblock %}

 {% block body %}
    <div class="page-title-overlap bg-dark pt-4">
      <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
        <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
          <nav aria-label="breadcrumb">


            <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
              <li class="breadcrumb-item"><a class="text-nowrap" href="index.html"><i class="ci-home"></i>Home</a></li>
              <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
              </li>

              <li class="breadcrumb-item text-nowrap active" aria-current="page">{% block profil_navigation %} Profile info {% endblock %}</li>

            </ol>
          </nav>
        </div>
        <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
          <h1 class="h3 text-light mb-0">
            {% block baslik %}
            Profile info {% endblock %}</h1>
        </div>
      </div>
    </div>
    <div class="container pb-5 mb-2 mb-md-4">
      <div class="row">
        <!-- Sidebar-->
        <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
          <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
            <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
              <div class="d-md-flex align-items-center">
                <div class=" rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><span class="badge bg-warning position-absolute end-0 mt-n2" data-bs-toggle="tooltip" title="Reward points"></span>
                 <!-- IF USER DOESNT HAVE IMAGE  -->
                  {% if request.user.profile.image != 'default.jpg' %}
                         <img src="{{ request.user.profile.image.url }}" class="rounded" width="70" alt="">
                </div>
                  {% else %}
                  <p class="" id="profileImage" style="background-color:{{ request.user.profile.bg_color }}" ><span class="text text-center">{{ request.user.first_name.0}}{{request.user.last_name.0}}</span></p></div>
                  {% endif %}
                <div class="ps-md-3">
                  <h3 class="fs-base mb-0">{{ request.user.first_name|title }} {{ request.user.last_name|title }}</h3><span class="text-accent fs-sm">{{ request.user.email }}</span>
                </div>
              </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
            </div>
            <div class="d-lg-block collapse" id="account-menu">
              <div class="bg-secondary px-4 py-3">
                <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
              </div>
              <!-- Active Class olayı için alttaki url as ler -->
              {% url 'destek' as destek %}
              {% url 'profile' as profile %}

              <ul class="list-unstyled mb-0">
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="account-orders.html"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="account-wishlist.html"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
                <li class="mb-0"><a  {% if request.path == destek %} class= "nav-link-style d-flex align-items-center px-4 py-3 active " {% else %} class= "nav-link-style d-flex align-items-center px-4 py-3" {% endif %} href="{% url 'destek' %}"><i class="ci-help opacity-60 me-2"></i>Support tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              </ul>
              <div class="bg-secondary px-4 py-3">
                <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
              </div>
              <ul class="list-unstyled mb-0">


                
                <li class="border-bottom mb-0"><a {% if request.path == profile %} class= "nav-link-style d-flex align-items-center px-4 py-3 active "   {% else %} class= "nav-link-style d-flex align-items-center px-4 py-3 " {% endif %} href="{% url 'profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="account-address.html"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
                <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="account-payment.html"><i class="ci-card opacity-60 me-2"></i>Payment methods</a></li>
                <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
              </ul>
            </div>
          </div>
        </aside>
        <!-- Content  -->
        <section class="col-lg-8">
          <!-- Toolbar-->
          <div class="d-none d-lg-flex justify-content-between align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3">
          {% block ust_icerik %}  <h6 class="fs-base text-light mb-0">{% block sayfa_baslik %} Profilinizi Güncelleyin {% endblock %}</h6>{% endblock %}<a class="btn btn-primary btn-sm" href="{% url 'logout' %}"><i class="ci-sign-out me-2"></i>Sign out</a>
          </div>
          <!-- Profile form-->
              {% block profile_body %}
          TEST
              {% endblock %}
        </section>
      </div>
    </div>
 {% endblock %}

{% block vue %}
{% endblock %}

templates/kullanici/profile/single-ticket.html
{% extends 'kullanici/profile/profile_base.html' %}

{% load static %}

{% block profile_body %}

{% for mesaj in mesajlar %}

{% if mesaj.is_staff == True %}
<div class="d-flex align-items-start py-4 border-bottom mt-4"><img class="rounded-circle" src="{% static 'img/about/helpdesk-avatar.jpg' %}" width="50" alt="Michael Davis">
            <div class="ps-3">
              <h6 class="fs-md mb-2">Site Görevlisi</h6>
              <p class="fs-md mb-1">{{ mesaj.msg_text }}</p><span class="fs-ms text-muted"><i class="ci-time align-middle me-2"></i>{{ mesaj.message_time }}</span>
            </div>
</div>

                {% else %}
              <!-- Comment-->
              <div class="d-flex align-items-start border-bottom py-4 mt-4"><img class="rounded-circle" src="{{ request.user.profile.image.url }}" width="50" alt="Susan Gardner">
                <div class="ps-3">
                  <h6 class="fs-md mb-2">{{ request.user.first_name|title }} {{ request.user.last_name|title }}</h6>
                  <p class="fs-md mb-1">{{ mesaj.msg_text }}</p><span class="fs-ms text-muted"><i class="ci-time align-middle me-2"></i>{{ mesaj.message_time }}</span>
                </div>
              </div>
                {% endif %}



{% endfor %}

<h3 class="h5 mt-2 pt-4 pb-2">Mesaj Bırakın</h3>
          <form class="needs-validation" action="{% url 'single-ticket' chat.id %}" method="POST" novalidate>
              {% csrf_token %}
            <div class="mb-3">
              {% for field in mesaj_form %}
                    {{ field }}
                    {% endfor %}
                {% include 'base/form_errors.html' %}
            </div>
            <div class="d-flex flex-wrap justify-content-between align-items-center">
              <div class="form-check">

              </div>
              <button class="btn btn-primary my-2" type="submit">Submit message</button>
            </div>
          </form>








{% endblock %}
{% block profil_navigation %}
Destek Mesajları
{% endblock %}
{% block ust_icerik %}
 <div class="d-flex w-100 text-light text-center me-3">
              <div class="fs-ms px-3">
                <div class="fw-medium">Date Submitted</div>
                <div class="opacity-60">{{ chat.created_time }}</div>
              </div>

              <div class="fs-ms px-3">
                <div class="fw-medium">Type</div>
                <div class="opacity-60">{{ chat.message_type }}</div>
              </div>
                <div class="fs-ms px-3">
                <div class="fw-medium">Subject</div>
                <div class="opacity-60">{{ chat.subject }}</div>
              </div>
              <div class="fs-ms px-3">
                <div class="fw-medium">Priority</div><span class="badge bg-{{ chat.priority }}">
                     {% if chat.priority == 'danger' %}
                        Acil
                      {% elif chat.priority == 'warning' %}
                        Yüksek
                      {% elif chat.priority == 'info' %}
                        Orta
                    {% elif chat.priority == 'success' %}
                      Düşük
                    {% endif %}
              </span>
              </div>

            </div>

{% endblock %}
{% block baslik %}
Destek Talepleri
{% endblock %}

{% block sayfa_baslik %}

{% endblock %}